package barata.mps.rootLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.SConceptId;

public class ConstraintsAspectDescriptor implements jetbrains.mps.smodel.runtime.ConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }
  public ConstraintsDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_2qnle6_a0a0b, fqName)) {
      case 0:
        return new DAOChildMapper_Constraints();
      case 1:
        return new DAOEntityMapper_Constraints();
      case 2:
        return new DAOPropertyMapper_Constraints();
      case 3:
        return new DAOReferenceMapper_Constraints();
      case 4:
        return new EntityType_Constraints();
      default:
        return new BaseConstraintsDescriptor(fqName);
    }
  }
  public ConstraintsDescriptor getDescriptor(SConceptId conceptId) {
    long id = conceptId.getIdValue();
    if (id == 0x17ad7b245711b2c1L) {
      return new DAOChildMapper_Constraints();
    }
    if (id == 0x25b0b61fcc326122L) {
      return new DAOEntityMapper_Constraints();
    }
    if (id == 0x25b0b61fcc325f03L) {
      return new DAOPropertyMapper_Constraints();
    }
    if (id == 0x17ad7b2456d2b6a7L) {
      return new DAOReferenceMapper_Constraints();
    }
    if (id == 0x64e3288c48324fa3L) {
      return new EntityType_Constraints();
    }
    return new BaseConstraintsDescriptor(conceptId);
  }
  private static String[] stringSwitchCases_2qnle6_a0a0b = new String[]{"barata.mps.rootLanguage.structure.DAOChildMapper", "barata.mps.rootLanguage.structure.DAOEntityMapper", "barata.mps.rootLanguage.structure.DAOPropertyMapper", "barata.mps.rootLanguage.structure.DAOReferenceMapper", "barata.mps.rootLanguage.structure.EntityType"};
}
