package barata.mps.businessObjectLanguage;

/*Generated by MPS */

import jetbrains.mps.smodel.language.LanguageRuntime;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;
import java.util.UUID;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.smodel.runtime.LanguageAspectDescriptor;
import jetbrains.mps.smodel.runtime.StructureAspectDescriptor;

public class Language extends LanguageRuntime {
  public static String MODULE_REF = "9e0b0b77-694a-456b-9778-612dc9764764(barata.mps.businessObjectLanguage)";
  public Language() {
  }
  @Override
  public String getNamespace() {
    return "barata.mps.businessObjectLanguage";
  }

  @Override
  public int getVersion() {
    return 0;
  }

  public SLanguageId getId() {
    return new SLanguageId(UUID.fromString("9e0b0b77-694a-456b-9778-612dc9764764"));
  }
  @Override
  protected String[] getExtendedLanguageIDs() {
    return new String[]{"barata.mps.rootLanguage"};
  }
  @Override
  public Collection<TemplateModule> getGenerators() {
    return TemplateUtil.<TemplateModule>asCollection(TemplateUtil.createInterpretedGenerator(this, "1a09c152-fa53-4e45-9cdb-eeff24c668f5(barata.mps.businessObjectLanguage#5946678282182456240)"));
  }
  @Override
  protected <T extends LanguageAspectDescriptor> T createAspectDescriptor(Class<T> descriptorClass) {
    if (descriptorClass == StructureAspectDescriptor.class) {
      return (T) new barata.mps.businessObjectLanguage.structure.StructureAspectDescriptor();
    }
    return super.createAspectDescriptor(descriptorClass);
  }
}
