package barata.mps.databaseOperationsLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class AbstractValue_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AbstractValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.databaseOperationsLanguage.structure.AbstractValue";
  }
}
