package barata.mps.databaseOperationsLanguage.behavior;

/*Generated by MPS */


public class BooleanValue_BehaviorDescriptor extends AbstractValue_BehaviorDescriptor {
  public BooleanValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.databaseOperationsLanguage.structure.BooleanValue";
  }
}
