package barata.mps.databaseOperationsLanguage.behavior;

/*Generated by MPS */


public class DeleteOperation_BehaviorDescriptor extends Operation_BehaviorDescriptor {
  public DeleteOperation_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.databaseOperationsLanguage.structure.DeleteOperation";
  }
}
