package barata.mps.databaseOperationsLanguage.behavior;

/*Generated by MPS */


public class InsertOperation_BehaviorDescriptor extends Operation_BehaviorDescriptor {
  public InsertOperation_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.databaseOperationsLanguage.structure.InsertOperation";
  }
}
