package barata.mps.databaseOperationsLanguage.behavior;

/*Generated by MPS */


public class IntValue_BehaviorDescriptor extends AbstractValue_BehaviorDescriptor {
  public IntValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.databaseOperationsLanguage.structure.IntValue";
  }
}
