package barata.mps.databaseOperationsLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class PropertyReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PropertyReference_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.databaseOperationsLanguage.structure.PropertyReference";
  }
}
