package barata.mps.databaseOperationsLanguage.behavior;

/*Generated by MPS */


public class UpdateOperation_BehaviorDescriptor extends Operation_BehaviorDescriptor {
  public UpdateOperation_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.databaseOperationsLanguage.structure.UpdateOperation";
  }
}
