package barata.mps.rootLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Attribute_Behavior {
  public static void init(SNode thisNode) {
  }
  public static String call_getCamelName_7227310691964504580(SNode thisNode) {
    String nodeName = SPropertyOperations.getString(thisNode, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    String firstLetter = nodeName.substring(0, 1).toUpperCase();
    String restOfName = nodeName.substring(1, nodeName.length());
    return firstLetter + restOfName;
  }
}
