package barata.mps.rootLanguage.behavior;

/*Generated by MPS */


public class BooleanType_BehaviorDescriptor extends PrimaryType_BehaviorDescriptor {
  public BooleanType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.rootLanguage.structure.BooleanType";
  }
}
