package barata.mps.rootLanguage.behavior;

/*Generated by MPS */


public class DAOChildMapper_BehaviorDescriptor extends Attribute_BehaviorDescriptor {
  public DAOChildMapper_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.rootLanguage.structure.DAOChildMapper";
  }
}
