package barata.mps.rootLanguage.behavior;

/*Generated by MPS */


public class DAOEntity_BehaviorDescriptor extends Entity_BehaviorDescriptor {
  public DAOEntity_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.rootLanguage.structure.DAOEntity";
  }
}
