package barata.mps.rootLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class DAOMapping_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DAOMapping_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.rootLanguage.structure.DAOMapping";
  }
}
