package barata.mps.rootLanguage.behavior;

/*Generated by MPS */


public class DAOPropertyMapper_BehaviorDescriptor extends Attribute_BehaviorDescriptor {
  public DAOPropertyMapper_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.rootLanguage.structure.DAOPropertyMapper";
  }
}
