package barata.mps.rootLanguage.behavior;

/*Generated by MPS */


public class DAOReferenceMapper_BehaviorDescriptor extends Attribute_BehaviorDescriptor {
  public DAOReferenceMapper_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.rootLanguage.structure.DAOReferenceMapper";
  }
}
