package barata.mps.rootLanguage.behavior;

/*Generated by MPS */


public class EntityType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public EntityType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.rootLanguage.structure.EntityType";
  }
}
