package barata.mps.rootLanguage.behavior;

/*Generated by MPS */


public class IntType_BehaviorDescriptor extends PrimaryType_BehaviorDescriptor {
  public IntType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.rootLanguage.structure.IntType";
  }
}
