package barata.mps.rootLanguage.behavior;

/*Generated by MPS */


public abstract class PrimaryType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public PrimaryType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.rootLanguage.structure.PrimaryType";
  }
}
