package barata.mps.rootLanguage.behavior;

/*Generated by MPS */


public class StringType_BehaviorDescriptor extends PrimaryType_BehaviorDescriptor {
  public StringType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.rootLanguage.structure.StringType";
  }
}
