package barata.mps.businessObjectLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import barata.mps.rootLanguage.behavior.DAOObject_BehaviorDescriptor;

public class Shop_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements DAOObject_BehaviorDescriptor {
  public Shop_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "barata.mps.businessObjectLanguage.structure.Shop";
  }
}
