package barata.mps.rootLanguage.sandbox;

/*Generated by MPS */

import java.sql.SQLException;

public class DBCommands {

  public static void executeCommands() throws ClassNotFoundException, SQLException {
    PersonDAO personDAO = new PersonDAO();
    Person person = new Person();
    person = new Person();
    person.setId(4);
    person.setFirstName("Test1");
    person.setLastName("Test2");
    personDAO.addPerson(person);
  }

  public static void main(String[] args) {
    try {
      executeCommands();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
