package barata.mps.databaseOperationsLanguage.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import barata.mps.databaseOperationsLanguage.behavior.PropertyReference_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import barata.mps.databaseOperationsLanguage.behavior.DBCommands_Behavior;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;
  public static Object propertyMacro_GetPropertyValue_6352133620898950334(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase() + "DAO";
  }
  public static Object propertyMacro_GetPropertyValue_6352133620899018275(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase();
  }
  public static Object propertyMacro_GetPropertyValue_6352133620905393715(final PropertyMacroContext _context) {
    return "new" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_8274062575490655497(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf876b84baL, 0x58274fdf876b84d6L, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_8274062575490656408(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf876b8483L, 0x58274fdf876b84b3L, "value"));
  }
  public static Object referenceMacro_GetReferent_6352133620898949187(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "DAO";
  }
  public static Object referenceMacro_GetReferent_6352133620898951692(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "DAO";
  }
  public static Object referenceMacro_GetReferent_6352133620898964737(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_6352133620898965629(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_6352133620899769774(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_6352133620899764074(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6352133620899765503(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6352133620899774277(final ReferenceMacroContext _context) {
    return PropertyReference_Behavior.call_generateSetter_6352133620899896357(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875b2b4eL, 0x58274fdf8771052cL, "searchReference")));
  }
  public static Object referenceMacro_GetReferent_6352133620899686938(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase() + "DAO";
  }
  public static Object referenceMacro_GetReferent_6352133620899714209(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6352133620899706935(final ReferenceMacroContext _context) {
    String name = SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    name = name.substring(0, 1).toUpperCase() + name.substring(1, name.length());
    return "delete" + name;
  }
  public static Object referenceMacro_GetReferent_6352133620905359257(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_6352133620905359267(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6352133620905359281(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, "barata.mps.databaseOperationsLanguage.structure.Operation")), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6352133620905359304(final ReferenceMacroContext _context) {
    return PropertyReference_Behavior.call_generateSetter_6352133620899896357(_context.getNode());
  }
  public static Object referenceMacro_GetReferent_6352133620905359321(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase() + "DAO";
  }
  public static Object referenceMacro_GetReferent_6352133620905359336(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6352133620905359347(final ReferenceMacroContext _context) {
    String name = SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    name = name.substring(0, 1).toUpperCase() + name.substring(1, name.length());
    return "add" + name;
  }
  public static Object referenceMacro_GetReferent_6352133620899881899(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_6352133620899881909(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6352133620905416380(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6352133620905419911(final ReferenceMacroContext _context) {
    return PropertyReference_Behavior.call_generateSetter_6352133620899896357(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875fd70dL, 0x58274fdf87710544L, "searchReference")));
  }
  public static Object referenceMacro_GetReferent_6352133620905392587(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_6352133620905393090(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_6352133620899907324(final ReferenceMacroContext _context) {
    return "new" + SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, "barata.mps.databaseOperationsLanguage.structure.Operation")), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_6352133620899909864(final ReferenceMacroContext _context) {
    return PropertyReference_Behavior.call_generateSetter_6352133620899896357(_context.getNode());
  }
  public static Object referenceMacro_GetReferent_6352133620899881955(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase() + "DAO";
  }
  public static Object referenceMacro_GetReferent_6352133620899881970(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6352133620905488141(final ReferenceMacroContext _context) {
    return "new" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_6352133620899881981(final ReferenceMacroContext _context) {
    String name = SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875ad2a1L, 0x58274fdf875b2b4cL, "object")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
    name = name.substring(0, 1).toUpperCase() + name.substring(1, name.length());
    return "update" + name;
  }
  public static SNode sourceNodeQuery_6352133620899816334(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875b2b4eL, 0x58274fdf8771052cL, "searchReference")), MetaAdapterFactory.getContainmentLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875fd58eL, 0x58274fdf875fd5cfL, "value"));
  }
  public static SNode sourceNodeQuery_6352133620905359297(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875fd58eL, 0x58274fdf875fd5cfL, "value"));
  }
  public static SNode sourceNodeQuery_6352133620905464114(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875fd70dL, 0x58274fdf87710544L, "searchReference")), MetaAdapterFactory.getContainmentLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875fd58eL, 0x58274fdf875fd5cfL, "value"));
  }
  public static SNode sourceNodeQuery_6352133620899913323(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875fd58eL, 0x58274fdf875fd5cfL, "value"));
  }
  public static Iterable<SNode> sourceNodesQuery_6352133620898946946(final SourceSubstituteMacroNodesContext _context) {
    return DBCommands_Behavior.call_getNonDupplicates_6352133620898804729(_context.getNode());
  }
  public static Iterable<SNode> sourceNodesQuery_6352133620898962658(final SourceSubstituteMacroNodesContext _context) {
    return DBCommands_Behavior.call_getNonDupplicates_6352133620898804729(_context.getNode());
  }
  public static Iterable<SNode> sourceNodesQuery_6352133620899681288(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875fd81bL, 0x58274fdf875fd837L, "operations"));
  }
  public static Iterable<SNode> sourceNodesQuery_6352133620905359311(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875fd520L, 0x58274fdf875fd5d6L, "propertyReferences"));
  }
  public static Iterable<SNode> sourceNodesQuery_6352133620899906605(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x24049aed5c4a4cc1L, 0x8e5cdbabbadbe5eeL, 0x58274fdf875fd70dL, 0x58274fdf875fd74aL, "propertyReferences"));
  }
}
