package barata.mps.rootLanguage.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class RemoveDupplicates_QuickFix extends QuickFix_Runtime {
  public RemoveDupplicates_QuickFix() {
  }
  public String getDescription(SNode node) {
    return "Remove dupplicate";
  }
  public void execute(SNode node) {
    SNodeOperations.deleteNode(node);
  }
}
